//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string mobile { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
